version: '2'
services:
  ntrip-proxy:
    image: ntrip-proxy
    build: proxy
    ports:
      - "8082:80"
    environment:
      NTRIP_DOMAIN: $NTRIP_DOMAIN
      NTRIP_USER: $NTRIP_USER
      NTRIP_PASS: $NTRIP_PASS
      NTRIP_HTTP_PROTOCOL: $NTRIP_HTTP_PROTOCOL
  rtklib-str2str:
    image: rtklib
    build: rtklib
    ports:
      - "6000:6000"
    command: [
      "str2str",
      "-in", "ntrip://ntrip-proxy:80/${NTRIP_MOUNT_POINT}#rtcm3",
      "-msg", "1057,1058,1059,1063,1064,1065",
      "-out", "tcpsvr://:6000",
      "-r", "100",
      "-s", "100000000"]
    environment:
      NTRIP_MOUNT_POINT: $NTRIP_MOUNT_POINT
